#!/bin/bash

## Variables. Common values to be used throughout the program
home=~
config_file=.psyncer


##
# Triggers all the actions
#
do_psyncer () {
    check_for_rsync
    check_for_local_config_file
}

##
# The psyncer utility will work as a bundle of commands. So, the first argument is mandatory to make things works
#
check_for_first_argument() {
    if [ -z $1 ]; then
        echo You must provides the first argument to tell to the utility what you want to do.
    fi
}

##
# Check for rsync program. It is a prerequisite. It not, quit.
#
check_for_rsync() {
    if ! which rsync > /dev/null 2>&1; then
        echo You need the rsync utility installed in the system.
        exit 1
    fi
}

check_for_local_config_file () {
    if [ ! -f $home/$config_file ]; then
        echo There\'s have any local configuration file.
        exit 1
    fi
}

do_psyncer